version: "3.8"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - scapp-net

networks:
  scapp-net:
    external: true
