version: "3.8"

services:
  sc_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - uploads_data:/app/uploads
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

volumes:
  uploads_data:
