version: '3.9'

services:
  sc_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sc_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
    networks:
      - backend_net

networks:
  backend_net:
    driver: bridge

